#!/bin/python

import error_handling
import sys
from ai import AI
from communication import Communication
from utils import connexion_server, connexion_team


def loop_client(dict_args):
    """ Loop client

    Args:
        dict_args (dict): dictionnary of informations entered by users
    """
    message = ""
    s = connexion_server(dict_args["port"], dict_args["machine"])
    communication = Communication(s)
    connexion_team(s, dict_args)
    bot = AI(communication, dict_args["name"])
    if bot.run() == "forked":
        loop_client(dict_args)


if __name__ == "__main__":
    dict_argument = {}
    error_handling.error_handler(sys.argv[1:], dict_argument)
    loop_client(dict_argument)
    # print("qUIT\n")
    # # try:
    # except Exception as error:
    #     print(error, file=sys.stderr)
    #     sys.exit(84)
    # sys.exit(0)
